export enum DeviceType {
  Display = 'display',
  Amplifier = 'amplifier',
  Player = 'player',
  Other = 'other',
}

export enum RemoteButton {
  PowerOn = 'powerOn',
  PowerOff = 'powerOff',
  PowerToggle = 'powerToggle',
  VolumeUp = 'volumeUp',
  VolumeDown = 'volumeDown',
  Mute = 'mute',
  ChannelUp = 'channelUp',
  ChannelDown = 'channelDown',
  Input = 'input',
  Up = 'up',
  Down = 'down',
  Left = 'left',
  Right = 'right',
  Ok = 'ok',
  Back = 'back',
  Home = 'home',
  Menu = 'menu',
  Play = 'play',
  Pause = 'pause',
  Stop = 'stop',
  Forward = 'forward',
  Rewind = 'rewind',
  Record = 'record',
  Number0 = 'number0',
  Number1 = 'number1',
  Number2 = 'number2',
  Number3 = 'number3',
  Number4 = 'number4',
  Number5 = 'number5',
  Number6 = 'number6',
  Number7 = 'number7',
  Number8 = 'number8',
  Number9 = 'number9',
}
