export const commandTypeOptions = [
  { value: "ir", label: "Infrared" },
  { value: "bluetooth", label: "Bluetooth" },
  { value: "network", label: "Network" },
  { value: "integration", label: "Integration" },
  { value: "script", label: "Script" },
];

export const commandGroupOptions = [
  { value: "volume", label: "Volume" },
  { value: "navigation", label: "Navigation" },
  { value: "transport", label: "Transport" },
  { value: "colored_buttons", label: "Colors" },
  { value: "channel", label: "Channel" },
  { value: "power", label: "Power" },
  { value: "numeric", label: "Numeric" },
  { value: "input", label: "Input" },
  { value: "other", label: "Other" },
];

type Option = { value: string; label: string };

export const buttonOptionsByGroup: Record<string, Option[]> = {
  power: [
    { value: "power_toggle", label: "Power toggle" },
    { value: "power_on", label: "Power on" },
    { value: "power_off", label: "Power off" },
  ],
  volume: [
    { value: "volume_up", label: "Volume up" },
    { value: "volume_down", label: "Volume down" },
    { value: "mute", label: "Mute" },
  ],
  navigation: [
    { value: "direction_up", label: "Up" },
    { value: "direction_down", label: "Down" },
    { value: "direction_left", label: "Left" },
    { value: "direction_right", label: "Right" },
    { value: "select", label: "Select" },
    { value: "back", label: "Back" },
    { value: "menu", label: "Menu" },
    { value: "exit", label: "Exit" },
    { value: "guide", label: "Guide" },
  ],
  transport: [
    { value: "playpause", label: "Play/Pause" },
    { value: "play", label: "Play" },
    { value: "pause", label: "Pause" },
    { value: "stop", label: "Stop" },
    { value: "fast_forward", label: "Fast forward" },
    { value: "rewind", label: "Rewind" },
    { value: "next_track", label: "Next track" },
    { value: "previous_track", label: "Previous track" },
    { value: "record", label: "Record" },
  ],
  channel: [
    { value: "channel_up", label: "Channel up" },
    { value: "channel_down", label: "Channel down" },
  ],
  numeric: [
    { value: "number_zero", label: "0" },
    { value: "number_one", label: "1" },
    { value: "number_two", label: "2" },
    { value: "number_three", label: "3" },
    { value: "number_four", label: "4" },
    { value: "number_five", label: "5" },
    { value: "number_six", label: "6" },
    { value: "number_seven", label: "7" },
    { value: "number_eight", label: "8" },
    { value: "number_nine", label: "9" },
  ],
  input: [{ value: "other", label: "Other" }],
  colored_buttons: [
    { value: "green", label: "Green" },
    { value: "red", label: "Red" },
    { value: "blue", label: "Blue" },
    { value: "yellow", label: "Yellow" },
  ],
  other: [
    { value: "brightness_up", label: "Brightness up" },
    { value: "brightness_down", label: "Brightness down" },
    { value: "turn_on", label: "Turn on" },
    { value: "turn_off", label: "Turn off" },
    { value: "other", label: "Other" },
  ],
};

export const getButtonOptions = (group: string) =>
  buttonOptionsByGroup[group] ?? buttonOptionsByGroup.other;

export const getButtonLabel = (group: string, button: string) =>
  getButtonOptions(group).find((option) => option.value === button)?.label ??
  button;

export const getGroupLabel = (group: string) =>
  commandGroupOptions.find((option) => option.value === group)?.label ?? group;

export const getTypeLabel = (type: string) =>
  commandTypeOptions.find((option) => option.value === type)?.label ?? type;

export const networkMethodOptions = [
  { value: "get", label: "GET" },
  { value: "post", label: "POST" },
  { value: "delete", label: "DELETE" },
  { value: "head", label: "HEAD" },
  { value: "patch", label: "PATCH" },
  { value: "put", label: "PUT" },
];

export const integrationActionOptions = [
  { value: "toggle_light", label: "Toggle light" },
  { value: "brightness_up", label: "Brightness up" },
  { value: "brightness_down", label: "Brightness down" },
];

export const bluetoothKeyTypeOptions = [
  { value: "regular", label: "Regular key" },
  { value: "media", label: "Media key" },
];

export const bluetoothKeyOptions = [
  { value: "KEY_RESERVED", label: "Reserved" },
  { value: "KEY_ESC", label: "Escape" },
  { value: "KEY_1", label: "1" },
  { value: "KEY_2", label: "2" },
  { value: "KEY_3", label: "3" },
  { value: "KEY_4", label: "4" },
  { value: "KEY_5", label: "5" },
  { value: "KEY_6", label: "6" },
  { value: "KEY_7", label: "7" },
  { value: "KEY_8", label: "8" },
  { value: "KEY_9", label: "9" },
  { value: "KEY_0", label: "0" },
  { value: "KEY_MINUS", label: "Minus" },
  { value: "KEY_EQUAL", label: "Equal" },
  { value: "KEY_BACKSPACE", label: "Backspace" },
  { value: "KEY_TAB", label: "Tab" },
  { value: "KEY_Q", label: "Q" },
  { value: "KEY_W", label: "W" },
  { value: "KEY_E", label: "E" },
  { value: "KEY_R", label: "R" },
  { value: "KEY_T", label: "T" },
  { value: "KEY_Y", label: "Y" },
  { value: "KEY_U", label: "U" },
  { value: "KEY_I", label: "I" },
  { value: "KEY_O", label: "O" },
  { value: "KEY_P", label: "P" },
  { value: "KEY_LEFTBRACE", label: "Left brace" },
  { value: "KEY_RIGHTBRACE", label: "Right brace" },
  { value: "KEY_ENTER", label: "Enter" },
  { value: "KEY_LEFTCTRL", label: "Left Ctrl" },
  { value: "KEY_A", label: "A" },
  { value: "KEY_S", label: "S" },
  { value: "KEY_D", label: "D" },
  { value: "KEY_F", label: "F" },
  { value: "KEY_G", label: "G" },
  { value: "KEY_H", label: "H" },
  { value: "KEY_J", label: "J" },
  { value: "KEY_K", label: "K" },
  { value: "KEY_L", label: "L" },
  { value: "KEY_SEMICOLON", label: "Semicolon" },
  { value: "KEY_APOSTROPHE", label: "Apostrophe" },
  { value: "KEY_GRAVE", label: "Grave" },
  { value: "KEY_LEFTSHIFT", label: "Left Shift" },
  { value: "KEY_BACKSLASH", label: "Backslash" },
  { value: "KEY_Z", label: "Z" },
  { value: "KEY_X", label: "X" },
  { value: "KEY_C", label: "C" },
  { value: "KEY_V", label: "V" },
  { value: "KEY_B", label: "B" },
  { value: "KEY_N", label: "N" },
  { value: "KEY_M", label: "M" },
  { value: "KEY_COMMA", label: "Comma" },
  { value: "KEY_DOT", label: "Dot" },
  { value: "KEY_SLASH", label: "Slash" },
  { value: "KEY_RIGHTSHIFT", label: "Right Shift" },
  { value: "KEY_KPASTERISK", label: "Numpad *" },
  { value: "KEY_LEFTALT", label: "Left Alt" },
  { value: "KEY_SPACE", label: "Space" },
  { value: "KEY_CAPSLOCK", label: "Caps lock" },
  { value: "KEY_F1", label: "F1" },
  { value: "KEY_F2", label: "F2" },
  { value: "KEY_F3", label: "F3" },
  { value: "KEY_F4", label: "F4" },
  { value: "KEY_F5", label: "F5" },
  { value: "KEY_F6", label: "F6" },
  { value: "KEY_F7", label: "F7" },
  { value: "KEY_F8", label: "F8" },
  { value: "KEY_F9", label: "F9" },
  { value: "KEY_F10", label: "F10" },
  { value: "KEY_NUMLOCK", label: "Num lock" },
  { value: "KEY_SCROLLLOCK", label: "Scroll lock" },
  { value: "KEY_KP7", label: "Numpad 7" },
  { value: "KEY_KP8", label: "Numpad 8" },
  { value: "KEY_KP9", label: "Numpad 9" },
  { value: "KEY_KPMINUS", label: "Numpad -" },
  { value: "KEY_KP4", label: "Numpad 4" },
  { value: "KEY_KP5", label: "Numpad 5" },
  { value: "KEY_KP6", label: "Numpad 6" },
  { value: "KEY_KPPLUS", label: "Numpad +" },
  { value: "KEY_KP1", label: "Numpad 1" },
  { value: "KEY_KP2", label: "Numpad 2" },
  { value: "KEY_KP3", label: "Numpad 3" },
  { value: "KEY_KP0", label: "Numpad 0" },
  { value: "KEY_KPDOT", label: "Numpad ." },
  { value: "KEY_ZENKAKUHANKAKU", label: "Zenkakuhankaku" },
  { value: "KEY_102ND", label: "102nd" },
  { value: "KEY_F11", label: "F11" },
  { value: "KEY_F12", label: "F12" },
  { value: "KEY_RO", label: "RO" },
  { value: "KEY_KATAKANA", label: "Katakana" },
  { value: "KEY_HIRAGANA", label: "Hiragana" },
  { value: "KEY_HENKAN", label: "Henkan" },
  { value: "KEY_KATAKANAHIRAGANA", label: "Katakana/Hiragana" },
  { value: "KEY_MUHENKAN", label: "Muhenkan" },
  { value: "KEY_KPJPCOMMA", label: "KP JP comma" },
  { value: "KEY_KPENTER", label: "Numpad Enter" },
  { value: "KEY_RIGHTCTRL", label: "Right Ctrl" },
  { value: "KEY_KPSLASH", label: "Numpad /" },
  { value: "KEY_SYSRQ", label: "SysRq" },
  { value: "KEY_RIGHTALT", label: "Right Alt" },
  { value: "KEY_HOME", label: "Home" },
  { value: "KEY_UP", label: "Arrow up" },
  { value: "KEY_PAGEUP", label: "Page up" },
  { value: "KEY_LEFT", label: "Arrow left" },
  { value: "KEY_RIGHT", label: "Arrow right" },
  { value: "KEY_END", label: "End" },
  { value: "KEY_DOWN", label: "Arrow down" },
  { value: "KEY_PAGEDOWN", label: "Page down" },
  { value: "KEY_INSERT", label: "Insert" },
  { value: "KEY_DELETE", label: "Delete" },
  { value: "KEY_MUTE", label: "Mute" },
  { value: "KEY_VOLUMEDOWN", label: "Volume down" },
  { value: "KEY_VOLUMEUP", label: "Volume up" },
  { value: "KEY_POWER", label: "Power" },
  { value: "KEY_KPEQUAL", label: "Numpad =" },
  { value: "KEY_PAUSE", label: "Pause" },
  { value: "KEY_KPCOMMA", label: "Numpad comma" },
  { value: "KEY_HANGEUL", label: "Hangeul" },
  { value: "KEY_HANJA", label: "Hanja" },
  { value: "KEY_YEN", label: "Yen" },
  { value: "KEY_LEFTMETA", label: "Left meta" },
  { value: "KEY_RIGHTMETA", label: "Right meta" },
  { value: "KEY_COMPOSE", label: "Compose" },
  { value: "KEY_STOP", label: "Stop" },
  { value: "KEY_AGAIN", label: "Again" },
  { value: "KEY_PROPS", label: "Props" },
  { value: "KEY_UNDO", label: "Undo" },
  { value: "KEY_FRONT", label: "Front" },
  { value: "KEY_COPY", label: "Copy" },
  { value: "KEY_OPEN", label: "Open" },
  { value: "KEY_PASTE", label: "Paste" },
  { value: "KEY_FIND", label: "Find" },
  { value: "KEY_CUT", label: "Cut" },
  { value: "KEY_HELP", label: "Help" },
  { value: "KEY_CALC", label: "Calc" },
  { value: "KEY_SLEEP", label: "Sleep" },
  { value: "KEY_WWW", label: "WWW" },
  { value: "KEY_COFFEE", label: "Coffee" },
  { value: "KEY_BACK", label: "Back" },
  { value: "KEY_FORWARD", label: "Forward" },
  { value: "KEY_EJECTCD", label: "Eject CD" },
  { value: "KEY_NEXTSONG", label: "Next song" },
  { value: "KEY_PLAYPAUSE", label: "Play/pause" },
  { value: "KEY_PREVIOUSSONG", label: "Previous song" },
  { value: "KEY_STOPCD", label: "Stop CD" },
  { value: "KEY_REFRESH", label: "Refresh" },
  { value: "KEY_EDIT", label: "Edit" },
  { value: "KEY_SCROLLUP", label: "Scroll up" },
  { value: "KEY_SCROLLDOWN", label: "Scroll down" },
  { value: "KEY_F13", label: "F13" },
  { value: "KEY_F14", label: "F14" },
  { value: "KEY_F15", label: "F15" },
  { value: "KEY_F16", label: "F16" },
  { value: "KEY_F17", label: "F17" },
  { value: "KEY_F18", label: "F18" },
  { value: "KEY_F19", label: "F19" },
  { value: "KEY_F20", label: "F20" },
  { value: "KEY_F21", label: "F21" },
  { value: "KEY_F22", label: "F22" },
  { value: "KEY_F23", label: "F23" },
  { value: "KEY_F24", label: "F24" },
];

export const bluetoothMediaKeyOptions = [
  { value: "KEY_PLAY", label: "Play" },
  { value: "KEY_PAUSE", label: "Pause" },
  { value: "KEY_PLAY_PAUSE", label: "Play/pause" },
  { value: "KEY_FAST_FORWARD", label: "Fast forward" },
  { value: "KEY_REWIND", label: "Rewind" },
  { value: "KEY_NEXT_TRACK", label: "Next track" },
  { value: "KEY_PREVIOUS_TRACK", label: "Previous track" },
  { value: "KEY_STOP", label: "Stop" },
  { value: "KEY_MENU", label: "Menu" },
  { value: "KEY_VOLUME_UP", label: "Volume up" },
  { value: "KEY_VOLUME_DOWN", label: "Volume down" },
  { value: "KEY_MUTE", label: "Mute" },
  { value: "KEY_POWER", label: "Power" },
  { value: "KEY_MENU_PICK", label: "Menu pick" },
  { value: "KEY_AC_SEARCH", label: "Search" },
  { value: "KEY_AC_HOME", label: "Home" },
];
